# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exiforge < Formula
  desc ""
  homepage ""
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soli0222/exiforge/releases/download/v2.1.0/exiforge_Darwin_x86_64.tar.gz"
      sha256 "582a9a0fcd6bc34a51868168fe1820cac505d89eaa5002808c183e846f8354a6"

      def install
        bin.install "exiforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soli0222/exiforge/releases/download/v2.1.0/exiforge_Darwin_arm64.tar.gz"
      sha256 "b9f6bf2e7127178d4f129eab5f1486d6a32a30ab098af146cb09443e7462cc7a"

      def install
        bin.install "exiforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Soli0222/exiforge/releases/download/v2.1.0/exiforge_Linux_x86_64.tar.gz"
        sha256 "064a8253742b86a13d9258e5da8572918c67b17d47cc96d044c0019bab9dddb9"

        def install
          bin.install "exiforge"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Soli0222/exiforge/releases/download/v2.1.0/exiforge_Linux_arm64.tar.gz"
        sha256 "4b74928555fe69ce5c3e70dc86179a43a2bacf2cefb3c6402e463aaf96f9f145"

        def install
          bin.install "exiforge"
        end
      end
    end
  end
end
